### ISSUE TITLE
[new page] migrating from a prior version

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#50] opened 2015-12-09 22:44 UTC
Originally: https://github.com/influxdb/influxdb.com/issues/349

We need to duplicate the 0.7 to 0.8 upgrade page with a doc on how to migrate from 0.8 to 0.9. Link to the import/export README, don't re-write it.

**Comment by marcellodesales** [comment] 2015-12-25 17:57
What's the migration? Maybe using a Docker command I can run to do that?

**Comment by beckettsean** [comment] 2015-12-28 19:11
@marcellodesales 0.8 to 0.9 is a highly manual migration. There is no way to fully automate it unless you have a trivial 0.8 schema.

**Comment by rkuchan** [comment] 2016-01-08 19:26
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/135. Duplicate of https://github.com/influxdata/docs.influxdata.com/issues/133

**Closed by rkuchan** 2016-01-08 19:26 UTC
