### ISSUE TITLE
Hardware Sizing, Memory Graph Missing Y Axis Values

### ISSUE THREAD

**Issue by r3cgm** [influxdata/docs.influxdata.com#483] opened 2016-05-31 16:15 UTC
Hi InfluxDB,

Just a quick note... at the URL below there is a nice graph showing the relationship between # of series vs. server memory, but the shape of the graph is just qualitative and does not have any specific memory values on the Y axis.  If it's supposed to be quantitative, could you put values there please?  Or if it's supposed to be qualitative you could remove the "(Gb)" units on the Y axis label. :)

###### URL for relevant page?

https://docs.influxdata.com/influxdb/v0.13/guides/hardware_sizing/

**Comment by r3cgm** [comment] 2016-05-31 16:15
Sorry, also meant to mention this is a great page.  Thanks for putting it together!

**Comment by beckettsean** [comment] 2016-06-02 21:38
closing as dupe of https://github.com/influxdata/docs.influxdata.com/issues/392

**Comment by beckettsean** [comment] 2016-06-02 21:39
@r3cgm thanks for liking the page! We're still working on getting actual numbers to publish, but they will always have lots of caveats. String length, schema, queries, and even number of retention policies all affect RAM in interdependent ways. Series cardinality is the primary driver, but not the only first-order effect.

**Closed by beckettsean** 2016-06-02 21:38 UTC
