### ISSUE TITLE
The 'Sample data' section is not wrapped nicely.

### ISSUE THREAD

**Issue by patrickcat** [influxdata/docs.influxdata.com#1411] opened 2018-02-07 08:45 UTC
The sample data rows/lines are not well formatted. Readers need to copy out the section and do a wrap manually. 

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.4/concepts/key_concepts/

###### What products and version are you using?
Influxdb v1.4

###### Where did you look before opening the issue?
n/a

**Comment by stevebang** [comment] 2018-02-26 22:09
Duplicate of #1410.

**Closed by stevebang** 2018-02-26 22:09 UTC
Labels: InfluxDB
