### ISSUE TITLE
[new page] instructions on setting up HTTPS #284

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#60] opened 2015-12-09 22:50 UTC
Originally: https://github.com/influxdb/influxdb.com/issues/

@toddboom 
I'm not sure we have this documented anywhere yet, but some quick instructions on how to set up a PEM file to work with InfluxDB for the HTTP API and the admin interface would be helpful. I'll add some notes here on how it should be laid out.

@victorhooi
For reference, this was the question I posted on the InfluxDB group about this issue:

https://groups.google.com/d/topic/influxdb/onlhVW9WJ-A/discussion

and it also contains the steps I followed.

It would be awesome if the proper way could be captured in the docs though.

I've managed to get the InfluxDb server-side working, now I'm hitting issue with the Influx CLI seemingly not liking the self-signed certs. Hopefully will be able to nut those out on the Google Group =).

**Comment by rkuchan** [comment] 2016-01-08 18:56
Closed as duplicate of https://github.com/influxdata/docs.influxdata.com/issues/91

**Closed by rkuchan** 2016-01-08 18:56 UTC
