### ISSUE TITLE
Key Concepts doc sample data is unformatted

### ISSUE THREAD

**Issue by seibar** [influxdata/docs.influxdata.com#1412] opened 2018-02-07 15:14 UTC
This page: https://docs.influxdata.com/influxdb/v1.4/concepts/key_concepts/

The data "Sample data" section is unformatted/misaligned.

**Comment by stevebang** [comment] 2018-02-26 22:10
Duplicate of #1410 -- thanks for catching this.

**Closed by stevebang** 2018-02-26 22:10 UTC
