### ISSUE TITLE
Newline in string field value

### ISSUE THREAD

**Issue by fs-aikito** [influxdata/docs.influxdata.com#2100] opened 2019-01-10 13:24 UTC
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_reference/
###### What products and version are you using?
InfluxDB 1.7
###### Where did you look before opening the issue?
Above manual page and https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/ which seems mostly duplicate of the reference

The line protocol reference does not specify how to properly escape a newline character in string field value. If it is not possible to do so, it would be useful to mention in the reference.

**Comment by kelseiv** [comment] 2019-03-20 21:23
Thank you, @fs-aikito! We added a note in the line protocol reference that newline character is not supported in string field values. Yes, the tutorial is mostly a duplicate of the reference--we're determining the best way to handle this case and duplicate content across the board.

**Closed by kelseiv** 2019-03-20 21:23 UTC
