### ISSUE TITLE
Docs are missing max-series-per-database setting

### ISSUE THREAD

**Issue by claytondukes** [influxdata/docs.influxdata.com#726] opened 2016-09-27 13:29 UTC
I am unable to locate the new "max-series-per-database" setting in the documentation.
![pasted image at 2016_09_27 09_21](https://cloud.githubusercontent.com/assets/12943165/18875706/e1f70a5c-8494-11e6-9568-120a9ce97a76.png)

**Comment by beckettsean** [comment] 2016-09-27 15:35
Dupe of https://github.com/influxdata/docs.influxdata.com/issues/710, which I've renamed to make it more obvious.

**Closed by beckettsean** 2016-09-27 15:35 UTC
