### ISSUE TITLE
Setting INFLUX_USERNAME/INFLUX_PASSWORD environment variables has no effect.

### ISSUE THREAD

**Issue by hraftery** [influxdata/docs.influxdata.com#1089] opened 2017-04-02 23:37 UTC
According to [this](https://docs.influxdata.com/influxdb/v1.2/query_language/authentication_and_authorization/#authenticate-requests), setting the INFLUX_USERNAME and INFLUX_PASSWORD environment variables should be enough to authenticate with the CLI. Alas, it appears to have no effect. Observe:

```
$ unset INFLUX_USERNAME
$ unset INFLUX_PASSWORD
$ echo $INFLUX_USERNAME $INFLUX_PASSWORD

$ influx -ssl -unsafeSsl
Connected to https://localhost:8086 version 1.2.1
InfluxDB shell version: 1.2.1
> use mydb
ERR: unable to parse authentication credentials
> exit

$ export INFLUX_USERNAME='admin'
$ export INFLUX_PASSWORD='password'
$ echo $INFLUX_USERNAME $INFLUX_PASSWORD
admin password
$ influx -ssl -unsafeSsl
Connected to https://localhost:8086 version 1.2.1
InfluxDB shell version: 1.2.1
> use mydb
ERR: unable to parse authentication credentials
> exit

$ influx -ssl -unsafeSsl -username $INFLUX_USERNAME -password $INFLUX_PASSWORD
Connected to https://localhost:8086 version 1.2.1
InfluxDB shell version: 1.2.1
> use mydb
Using database mydb
```

May be related to issue [7429](https://github.com/influxdata/influxdb/pull/7429).

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.2/query_language/authentication_and_authorization/#authenticate-requests

###### What products and version are you using?
InfluxDB 1.2.1

###### Where did you look before opening the issue?
Lots of Google links.

**Comment by timhallinflux** [comment] 2017-07-22 07:59
Can't reproduce.  Closing.

**Closed by timhallinflux** 2017-07-22 07:59 UTC

**Comment by hraftery** [comment] 2017-07-22 21:37
I can also can no longer reproduce. Same influx version, so not sure what's changed.

**Comment by timhallinflux** [comment] 2017-07-24 02:29
Not sure.  But, I think the good news is that this either has been addressed or there was something else going on.  It is not a documentation issue at this point and it doesn't appear to need a code fix either.

Have you tried 1.3.1 yet?  I'm going to close this out.
